//! Tool that AOT-compiles patch.zig

const std = @import("std");
const suzu = @import("suzu");

const patch = @import("patch.zig");

const compile = suzu.compile;
const Program = suzu.Program;

pub fn main(init: std.process.Init) !void {
    const gpa = init.gpa;
    const io = init.io;

    const args = try init.minimal.args.toSlice(init.arena.allocator());
    if (args.len != 2) {
        std.log.err("usage: bake <out_dir>", .{});
        std.process.exit(1);
    }

    var p = Program.init(gpa, patch.sample_rate);
    defer p.deinit();
    patch.build(&p) catch |err| {
        std.log.err("patch: {t}: {any}", .{ err, p.builder.diag });
        std.process.exit(1);
    };

    var dir = try std.Io.Dir.cwd().openDir(io, args[1], .{});
    defer dir.close(io);

    const object = try compile.compileAot(gpa, &p, "suzu_process", .{ .arch = .arm32, .format = .elf });
    defer gpa.free(object);
    try dir.writeFile(io, .{ .sub_path = "patch.o", .data = object });

    const memory = try gpa.alloc(u8, p.builder.memorySize());
    defer gpa.free(memory);
    p.builder.initMemory(memory);
    try dir.writeFile(io, .{ .sub_path = "memory.bin", .data = memory });

    const shared = try gpa.alloc(u8, compile.sharedMemorySize(&p));
    defer gpa.free(shared);
    const table = try gpa.alloc([*]const u8, compile.sharedMemCount(&p));
    defer gpa.free(table);
    compile.initSharedMemory(&p, shared, table);
    try dir.writeFile(io, .{ .sub_path = "shared.bin", .data = shared });

    var source: std.Io.Writer.Allocating = .init(gpa);
    defer source.deinit();
    try writeModule(&source.writer, &p, shared, table);
    try dir.writeFile(io, .{ .sub_path = "patch.zig", .data = source.written() });
}

fn writeModule(w: *std.Io.Writer, p: *const Program, shared: []const u8, table: []const [*]const u8) !void {
    try w.print(
        \\//! Generated by carts/suzu/bake.zig.
        \\
        \\pub const sample_rate = {d};
        \\
        \\pub const memory_size = {d};
        \\pub const memory_init: *const [memory_size]u8 = @embedFile("memory.bin");
        \\
        \\const shared_block: [{d}]u8 align(4) = @embedFile("shared.bin").*;
        \\pub const shared = [_][*]const u8{{
        \\
    , .{ patch.sample_rate, p.builder.memorySize(), shared.len });
    for (table) |base| {
        try w.print("    shared_block[{d}..].ptr,\n", .{@intFromPtr(base) - @intFromPtr(shared.ptr)});
    }
    try w.writeAll(
        \\};
        \\
        \\pub const Param = struct { offset: u32, min: f32, max: f32, default: f32 };
        \\
        \\pub const params = struct {
        \\
    );
    for (0..compile.paramCount(p)) |i| {
        const info = compile.param(p, i);
        try w.print("    pub const {s}: Param = .{{ .offset = {d}, .min = {d}, .max = {d}, .default = {d} }};\n", .{
            info.name,
            info.offset,
            info.min.float,
            info.max.float,
            info.default.float,
        });
    }
    try w.writeAll(
        \\};
        \\
        \\pub extern fn suzu_process(
        \\    ins: ?*const anyopaque,
        \\    outs: [*]const [*]f32,
        \\    frame_count: u32,
        \\    memory: [*]u8,
        \\    shared: [*]const [*]const u8,
        \\) callconv(.c) void;
        \\
    );
}
